Include resit exams in a scores chart
mirea-ninja/rtu-mirea-mobile pull request #276
Opened 2023-01-30 17:26 UTC by Eloren1

## Изменения

Исправлено отображение графика успеваемости для некоторых студентов.

## Пояснения

Неявка и долги теперь учитываются в среднем балле за семестр. Это решает проблему с отображением графика успеваемости для тех студентов, у которых не было оценок после прошедшей экзаменационной сессии.

2023-01-30 17:47 UTC, Dragonprod requested changes

2023-01-30 17:47 UTC, Dragonprod commented on lib/presentation/pages/profile/widgets/scores_chart_modal.dart
> +        return 1;
Судя по словам Ярослава Акатьева при неуде должен быть 0, а не 1

2023-01-30 18:21 UTC, Dragonprod approved these changes

2023-01-30 19:03 UTC, 0niel requested changes

2023-01-30 19:03 UTC, 0niel commented on lib/presentation/pages/profile/widgets/scores_chart_modal.dart
> -        if (scoreValue != -1) {
Теперь зачёты и прочие (если существуют) виды оценивания, отличные от `отлично`, `хорошо` и `удовлетворительно` учитываются как 0 при расчёте среднего балла, что портит итоговое значение.

Например, за семестр с оценками "отлично", "отлично", "зачтено", "зачтено" итоговый средний балл будет 2.5, а должен быть 5, иначе такое абстрактное значение не несёт никакой полезной информации.

Возможно, что возвращать 0 стоит только при наличии подстрок о соответствующей оценки, а в противном случае игнорировать при расчёте.

![image](https://user-images.githubusercontent.com/51058739/215570549-2e193f49-5306-422a-b89e-dc9c249794ba.png)

2023-01-31 10:27 UTC, 0niel approved these changes

2023-01-31 10:27 UTC, 0niel commented
Теперь похоже на правду. Спасибо!

2023-01-31 10:28 UTC, merged